---
argument_specs:
  main:
    options:
      cloudflare_zones:
        type: list
        required: true
        elements: dict
        options:
          name:
            required: true
            type: str
