---
- name: Ensure cloudflare zone {{ cloudflare_zone_name }}
  damex.cloudflare.cloudflare_zone:
    name: "{{ cloudflare_zone_name }}"
    account_name: "{{ cloudflare_zone_account_name }}"
    account_email: "{{ cloudflare_zone_account_email }}"
    account_api_key: "{{ cloudflare_zone_account_api_key }}"
    api_token: "{{ cloudflare_zone_api_token }}"
    state: "{{ cloudflare_zone_state }}"
    jump_start: "{{ cloudflare_zone_jump_start }}"
    type: "{{ cloudflare_zone_type }}"
    universal_ssl: "{{ cloudflare_zone_universal_ssl }}"
    ssl_mode: "{{ cloudflare_zone_ssl_mode }}"
    always_https: "{{ cloudflare_zone_always_https }}"
    min_tls_version: "{{ cloudflare_zone_min_tls_version }}"
