---
- name: Ensure cloudflare zones
  ansible.builtin.include_tasks: cloudflare_zone.yml
  vars:
    cloudflare_zone_name: "{{ cloudflare_zone.name }}"
    cloudflare_zone_account_name: "{{ cloudflare_zone.account_name | default(cloudflare_zones_account_name) }}"
    cloudflare_zone_account_email: "{{ cloudflare_zone.account_email | default(cloudflare_zones_account_email) | default(omit) }}"
    cloudflare_zone_account_api_key: "{{ cloudflare_zone.account_api_key | default(cloudflare_zones_account_api_key) | default(omit) }}"
    cloudflare_zone_api_token: "{{ cloudflare_zone.api_token | default(cloudflare_zones_api_token) | default(omit) }}"
    cloudflare_zone_state: "{{ cloudflare_zone.state | default(cloudflare_zones_default_state) }}"
    cloudflare_zone_jump_start: "{{ cloudflare_zone.jump_start | default(cloudflare_zones_default_jump_start) }}"
    cloudflare_zone_type: "{{ cloudflare_zone.type | default(cloudflare_zones_default_type) }}"
    cloudflare_zone_universal_ssl: "{{ cloudflare_zone.universal_ssl | default(cloudflare_zones_universal_ssl) | default(omit) }}"
    cloudflare_zone_ssl_mode: "{{ cloudflare_zone.ssl_mode | default(cloudflare_zones_ssl_mode) | default(omit) }}"
    cloudflare_zone_always_https: "{{ cloudflare_zone.always_https | default(cloudflare_zones_always_https) | default(omit) }}"
    cloudflare_zone_min_tls_version: "{{ cloudflare_zone.min_tls_version | default(cloudflare_zones_min_tls_version) | default(omit) }}"
  loop: "{{ cloudflare_zones }}"
  loop_control:
    label: "{{ cloudflare_zone_name }}"
    loop_var: cloudflare_zone
