---
namespace: damex
name: cloudflare
version: 1.0.0
readme: README.md
authors:
  - Roman Kuzmitskii <ansible@damex.org>
description: cloudflare collection
license_file: LICENSE
tags:
  - cloudflare
  - infrastructure
repository: https://github.com/damex/ansible-collections-cloudflare
issues: https://github.com/damex/ansible-collections-cloudflare/issues
dependencies:
  community.general: "*"
  community.crypto: "*"
