---
namespace: damex
name: cloudflare
version: 0.3.6
readme: README.md
authors:
  - Roman Kuzmitskii <ansible@damex.org>
license_file: LICENSE
tags:
  - cloudflare
repository: https://github.com/damex/ansible-collections-cloudflare
issues: https://github.com/damex/ansible-collections-cloudflare/issues
dependencies:
  community.general: "*"
  community.crypto: "*"
