---
- name: Ensure cloudflare DNS records for {{ cloudflare_dns_records_zone_name }}
  damex.cloudflare.cloudflare_dns_records:
    zone_name: "{{ cloudflare_dns_records_zone_name }}"
    api_token: "{{ cloudflare_dns_records_zone_api_token }}"
    account_email: "{{ cloudflare_dns_records_zone_account_email | default(omit) }}"
    account_api_key: "{{ cloudflare_dns_records_zone_account_api_key | default(omit) }}"
    records: "{{ cloudflare_dns_records_zone_records }}"
