---
- name: Ensure cloudflare DNS record {{ cloudflare_dns_record.record }}
  damex.cloudflare.cloudflare_dns_record:
    zone_name: "{{ cloudflare_dns_records_zone_name }}"
    api_token: "{{ cloudflare_dns_records_zone_api_token }}"
    account_email: "{{ cloudflare_dns_records_zone_account_email }}"
    account_api_key: "{{ cloudflare_dns_records_zone_account_api_key }}"
    record: "{{ cloudflare_dns_record.record }}"
    type: "{{ cloudflare_dns_record.type }}"
    content: "{{ cloudflare_dns_record.content | default(omit) }}"
    ttl: "{{ cloudflare_dns_record.ttl | default(cloudflare_dns_records_default_ttl) }}"
    priority: "{{ cloudflare_dns_record.priority | default(omit) }}"
    proxied: "{{ cloudflare_dns_record.proxied | default(cloudflare_dns_records_default_proxied) }}"
    state: "{{ cloudflare_dns_record.state | default(cloudflare_dns_records_default_state) }}"
