---
- name: Ensure cloudflare acme zones
  ansible.builtin.include_tasks: cloudflare_acme_zone_domains.yml
  vars:
    cloudflare_acme_zone_name: "{{ cloudflare_acme_zone.name }}"
    cloudflare_acme_zone_domains: "{{ cloudflare_acme_zone.domains }}"
    cloudflare_acme_zone_cloudflare_account_email: "{{ cloudflare_acme_zone.cloudflare_account_email | default(cloudflare_acme_cloudflare_account_email) | default(omit) }}"
    cloudflare_acme_zone_cloudflare_account_api_key: "{{ cloudflare_acme_zone.cloudflare_account_api_key | default(cloudflare_acme_cloudflare_account_api_key) | default(omit) }}"
    cloudflare_acme_zone_cloudflare_api_token: "{{ cloudflare_acme_zone.cloudflare_api_token | default(cloudflare_acme_cloudflare_api_token) | default(omit) }}"
    cloudflare_acme_zone_account_key_passphrase: "{{ cloudflare_acme_zone.account_key_passphrase | default(cloudflare_acme_account_key_passphrase) | default(omit) }}"
    cloudflare_acme_zone_certificate_directory: "{{ cloudflare_acme_zone.certificate_directory | default(cloudflare_acme_certificate_directory) }}"
    cloudflare_acme_zone_account_key_file: "{{ cloudflare_acme_zone.account_key_file | default(cloudflare_acme_zone_certificate_directory + '/' + cloudflare_acme_zone_name + '.account.key') }}"
    cloudflare_acme_zone_account_email: "{{ cloudflare_acme_zone.account_email | default(cloudflare_acme_account_email) | default(omit) }}"
    cloudflare_acme_zone_user: "{{ cloudflare_acme_zone.user | default(cloudflare_acme_user) }}"
    cloudflare_acme_zone_directory_url: "{{ cloudflare_acme_zone.directory_url | default(cloudflare_acme_directory_url) }}"
    cloudflare_acme_zone_deactivate_authzs: "{{ cloudflare_acme_zone.deactivate_authzs | default(cloudflare_acme_deactivate_authzs) }}"
  loop: "{{ cloudflare_acme_zones }}"
  loop_control:
    label: "{{ cloudflare_acme_zone_name }}"
    loop_var: cloudflare_acme_zone
