---
argument_specs:
  main:
    options:
      cloudflare_acme_certificate_directory:
        type: str
        required: true
      cloudflare_dns_zones:
        type: list
        required: true
        elements: dict
        options:
          name:
            required: true
            type: str
          domains:
            type: list
            required: true
            elements: dict
